// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-foreman/foreman/saga (interfaces: SagaUIDService)

// Package saga is a generated GoMock package.
package saga

import (
	reflect "reflect"

	message "github.com/go-foreman/foreman/pubsub/message"
	gomock "github.com/golang/mock/gomock"
)

// MockSagaUIDService is a mock of SagaUIDService interface.
type MockSagaUIDService struct {
	ctrl     *gomock.Controller
	recorder *MockSagaUIDServiceMockRecorder
}

// MockSagaUIDServiceMockRecorder is the mock recorder for MockSagaUIDService.
type MockSagaUIDServiceMockRecorder struct {
	mock *MockSagaUIDService
}

// NewMockSagaUIDService creates a new mock instance.
func NewMockSagaUIDService(ctrl *gomock.Controller) *MockSagaUIDService {
	mock := &MockSagaUIDService{ctrl: ctrl}
	mock.recorder = &MockSagaUIDServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSagaUIDService) EXPECT() *MockSagaUIDServiceMockRecorder {
	return m.recorder
}

// AddSagaId mocks base method.
func (m *MockSagaUIDService) AddSagaId(arg0 message.Headers, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSagaId", arg0, arg1)
}

// AddSagaId indicates an expected call of AddSagaId.
func (mr *MockSagaUIDServiceMockRecorder) AddSagaId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSagaId", reflect.TypeOf((*MockSagaUIDService)(nil).AddSagaId), arg0, arg1)
}

// ExtractSagaUID mocks base method.
func (m *MockSagaUIDService) ExtractSagaUID(arg0 message.Headers) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSagaUID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractSagaUID indicates an expected call of ExtractSagaUID.
func (mr *MockSagaUIDServiceMockRecorder) ExtractSagaUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSagaUID", reflect.TypeOf((*MockSagaUIDService)(nil).ExtractSagaUID), arg0)
}
