# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.5
      - image: circleci/mysql:8-ram
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: foreman
          MYSQL_USER: foreman
          MYSQL_PASSWORD: foreman
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: foreman
          POSTGRES_USER: foreman
          POSTGRES_PASSWORD: foreman
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            make mod-download
            make tools

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Lint
          command: |
            make lint
      - run:
          name: Check dependencies for vulnaribilties
          command: |
            make check-mods || true
      - run:
          name: Run tests
          environment:
            MYSQL_CONNECTION: foreman:foreman@tcp(127.0.0.1:3306)/foreman?charset=utf8&parseTime=True
            PG_CONNECTION:  postgres://foreman:foreman@127.0.0.1:5432/foreman?sslmode=disable
          command: |
            make unit-test
            make integration-test
      - run:
          name: Upload reports to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/test-reports
